### PR TITLE
upload files if all files are the right size

### PR DESCRIPTION
**Pull request by thescubageek**
* Fixes uploader to upload files if all are the correct size < 512kB
* Clears out filesArray after each successful or failed upload

PT: https://www.pivotaltracker.com/story/show/131772467
PT: https://www.pivotaltracker.com/story/show/130565721

### CODE REVIEW

**Comment by thescubageek** [comment]
@jcstringer This fixes the bugs found by @byronmil after the asset uploader cap related to duplicate files and failed upload for valid files

**Comment by thescubageek** [comment]
@jcstringer Not sure why the specs are failing -- but I'll add more specs around the all-valid upload and a confirmation that post-upload the filesArray is cleared

**Comment by thescubageek** [comment]
Also, I've told @byronmil that I'm done with Ember1 changes -- every time I switch I spend up to half an hour setting up the Ember env again (materialize and bower aren't playing nicely)

**Comment by jcstringer** [comment]
🚢  when 🍏  currently there is a failing spec

**Comment by thescubageek** [comment]
@jcstringer Specs are now 🍏 , ready to 🚢

**Pull request merged**
