### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by ceckert**
Small tweaks needed after merging.

### CODE REVIEW

**Comment by ceckert** [comment]
@levibrown can I get a quick PR? Some minor clean up after merging the single domain/single location deploy branch.

**Comment by levibrown** [comment]
why don't we need the deploy_all action?

**Comment by ceckert** [comment]
It is still there. I just removed the conditional which only displays it for Single Domain clients. Deploy All works for both SD and MD clients.

**Comment by levibrown** [comment]
:+1:

**Pull request merged**
