### PR TITLE
beta widgets

### PR DESCRIPTION
**Pull request by thescubageek**
* add beta to garden widget model, add tag to widget icons

CMS: https://github.com/g5search/g5-content-management-system/pull/2045

### CODE REVIEW

**Comment by thescubageek** [comment]
@jcstringer @levibrown One minor UX tweak I'm doing to the current Ember app so we can support Beta flags on GardenWidgets

**Comment by jcstringer** [comment]
@thescubageek can you port this over to the ember2 upgrade? I'll make a story for it.

**Comment by jcstringer** [comment]
https://www.pivotaltracker.com/story/show/131123685

**Comment by thescubageek** [comment]
@jcstringer Please review these changes to the Ember 1.0 app to allow for beta flags -- once approved and shipped I will migrate these to the Ember 2.0 effort. Thanks

**Comment by thescubageek** [comment]
@jcstringer This is shipping on Monday 10.10 so I'm going to merge into master of the Ember1 app now

**Pull request merged**
