### PR TITLE
cloudfront asset delete

### PR DESCRIPTION
**Pull request by thescubageek**
* add fullUrl to assets model, use fullUrl for deletes

PT: https://www.pivotaltracker.com/story/show/133616523
CMS: https://github.com/g5search/g5-content-management-system/pull/2214

### CODE REVIEW

**Comment by jcstringer** [comment]
Yup makes sense, just again maybe use a more meaningful attribute name and let's get the specs passing with the change.

**Comment by thescubageek** [comment]
@jcstringer This is a change to the Ember1.0 app, not the 2.0 -- I'll have another PR for that one if this works. Therefore, the specs won't pass because Ember1.0 has never had working specs.

**Comment by jcstringer** [comment]
🚢

**Comment by thescubageek** [comment]
@jcstringer Removing this PR since it is for the old cloudfront asset delete issue

**Pull request closed without merging**
